# Generated by Django 5.1.4 on 2025-02-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('Мастер П/О', 'Мастер П/О'), ('Преподователь', 'Преподователь'), ('Учебная часть', 'Учебная часть'), ('Директор', 'Директор'), ('Заместитель директора', 'Заместитель директора')], default='Преподователь', max_length=21, verbose_name='Должность'),
        ),
    ]
