# Generated by Django 5.1.4 on 2025-02-09 14:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('preview_img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('banner_img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('term', models.PositiveIntegerField(default=2, help_text='Срок обучения в месяцах', verbose_name='Срок обучения')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('preview_img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('banner_img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('term', models.PositiveIntegerField(default=2, help_text='Срок обучения в годах', verbose_name='Срок обучения')),
                ('contract', models.PositiveIntegerField(default=50000, verbose_name='Обучение на контрактной основе')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
    ]
