# Generated by Django 5.1.4 on 2025-02-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.PositiveIntegerField(default=2, help_text='Срок обучения в месяцах', verbose_name='Срок обучения'),
        ),
    ]
